[
{logradouro:"Avenida Jaime Nicolau Martins", bairro:"Centro", cep:"14775-021"},
{logradouro:"Avenida Jaime Nicolau Martins", bairro:"Conjunto Habitacional Luiz Ferreira", cep:"14775-030"},
{logradouro:"Avenida Jaime Nicolau Martins", bairro:"Conjunto Habitacional Noel Dionízio", cep:"14775-410"},
{logradouro:"Avenida Jaime Nicolau Martins", bairro:"Jardim Palmares", cep:"14775-082"},
{logradouro:"Avenida Jaime Nicolau Martins", bairro:"São Benedito", cep:"14775-378"},
{logradouro:"Avenida Jaime Nicolau Martins, 601 AC Jaborandi", bairro:"Centro", cep:"14775-970"},
{logradouro:"Avenida Jaime Nicolau Martins, 601 Clique e Retire Correios AC Jaborandi Clique e Retire", bairro:"Centro", cep:"14775-959"},
{logradouro:"Avenida Mastrelo", bairro:"COHAB CRHIS", cep:"14775-354"},
{logradouro:"Avenida Mastrelo", bairro:"Conjunto Habitacional Noel Dionízio", cep:"14775-400"},
{logradouro:"Avenida Mastrelo", bairro:"São Benedito", cep:"14775-396"},
{logradouro:"Praça Orlando Junqueira de Oliveira", bairro:"Centro", cep:"14775-019"},
{logradouro:"Praça São Benedito", bairro:"São Benedito", cep:"14775-376"},
{logradouro:"Rua Abrahão Abdala Azura", bairro:"Jaborandi", cep:"14775-130"},
{logradouro:"Rua Abrão Pinto Neto", bairro:"Conjunto Habitacional Agostinho Bruno", cep:"14775-338"},
{logradouro:"Rua Abrão Pinto Neto", bairro:"Conjunto Habitacional Antonio Baldo", cep:"14775-284"},
{logradouro:"Rua Abrão Pinto Neto", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-306"},
{logradouro:"Rua Abrão Pinto Neto", bairro:"Residencial Jaborandi I", cep:"14775-264"},
{logradouro:"Rua Alcides Apparecido Bergami", bairro:"Jardim Primavera", cep:"14775-154"},
{logradouro:"Rua Alcino Martino Mustafé", bairro:"Conjunto Habitacional Luiz Ferreira", cep:"14775-042"},
{logradouro:"Rua Alexandre de Avila Borges", bairro:"Centro", cep:"14775-007"},
{logradouro:"Rua Alexandre de Avila Borges", bairro:"Jaborandi", cep:"14775-140"},
{logradouro:"Rua Ally de Avila Junqueira", bairro:"Centro", cep:"14775-004"},
{logradouro:"Rua Ally de Avila Junqueira", bairro:"Conjunto Habitacional Luiz Ferreira", cep:"14775-044"},
{logradouro:"Rua Angelo Tornelli Sobrinho", bairro:"Conjunto Habitacional José Cardoso Batata", cep:"14775-206"},
{logradouro:"Rua Antônio Bruno", bairro:"Centro", cep:"14775-017"},
{logradouro:"Rua Antônio Bruno", bairro:"Jaborandi", cep:"14775-120"},
{logradouro:"Rua Antônio Bruno", bairro:"São Benedito", cep:"14775-374"},
{logradouro:"Rua Antônio Luiz de Lima", bairro:"Conjunto Habitacional Professora Mônica Borges Pagliuso", cep:"14775-058"},
{logradouro:"Rua Antônio Teodoro Nogueira", bairro:"Centro", cep:"14775-005"},
{logradouro:"Rua Anunciação de Jesus Pinto Neto", bairro:"Conjunto Habitacional Noel Dionízio", cep:"14775-408"},
{logradouro:"Rua Armando de Andréis", bairro:"Jardim Primavera", cep:"14775-156"},
{logradouro:"Rua Arthur Augusto de Oliveira", bairro:"Centro", cep:"14775-009"},
{logradouro:"Rua Arthur Augusto de Oliveira", bairro:"Conjunto Habitacional Professora Mônica Borges Pagliuso", cep:"14775-052"},
{logradouro:"Rua Arthur Augusto de Oliveira", bairro:"Jaborandi", cep:"14775-138"},
{logradouro:"Rua Arthur Augusto de Oliveira", bairro:"Jardim Palmares", cep:"14775-070"},
{logradouro:"Rua Arthur Augusto de Oliveira", bairro:"Jardim Primavera", cep:"14775-152"},
{logradouro:"Rua Assad Kalil Chabrour", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-320"},
{logradouro:"Rua Assad Kalil Chabrour", bairro:"Conjunto Habitacional Nossa Senhora Aparecida", cep:"14775-242"},
{logradouro:"Rua Assad Kalil Chabrour", bairro:"Conjunto Habitacional Ronan Sales Cardozo", cep:"14775-232"},
{logradouro:"Rua Atilio Brisigueli", bairro:"COHAB CRHIS", cep:"14775-356"},
{logradouro:"Rua Atilio Brisigueli", bairro:"Conjunto Habitacional Antonio Baldo", cep:"14775-288"},
{logradouro:"Rua Atilio Brisigueli", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-314"},
{logradouro:"Rua Atilio Brisigueli", bairro:"Residencial Jaborandi I", cep:"14775-268"},
{logradouro:"Rua Atilio Brisigueli", bairro:"São Benedito", cep:"14775-398"},
{logradouro:"Rua Benedito Adão", bairro:"COHAB CRHIS", cep:"14775-350"},
{logradouro:"Rua Benedito Adão", bairro:"Conjunto Habitacional Agostinho Bruno", cep:"14775-342"},
{logradouro:"Rua Benedito Adão", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-310"},
{logradouro:"Rua Carlos Oscar Vaz de Almeida", bairro:"Conjunto Habitacional Agostinho Bruno", cep:"14775-336"},
{logradouro:"Rua Carlos Oscar Vaz de Almeida", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-304"},
{logradouro:"Rua Colina", bairro:"COHAB CRHIS", cep:"14775-360"},
{logradouro:"Rua Colina", bairro:"Conjunto Habitacional Agostinho Bruno", cep:"14775-330"},
{logradouro:"Rua Colina", bairro:"Conjunto Habitacional Nossa Senhora Aparecida", cep:"14775-240"},
{logradouro:"Rua Colina", bairro:"Conjunto Habitacional Ronan Sales Cardozo", cep:"14775-234"},
{logradouro:"Rua Colina", bairro:"São Benedito", cep:"14775-370"},
{logradouro:"Rua Deocleciano Fogaça de Souza", bairro:"Conjunto Habitacional Agostinho Bruno", cep:"14775-332"},
{logradouro:"Rua Deocleciano Fogaça de Souza", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-300"},
{logradouro:"Rua Deocleciano Fogaça de Souza", bairro:"Conjunto Habitacional Nossa Senhora Aparecida", cep:"14775-248"},
{logradouro:"Rua Diamantino Cardozo", bairro:"Conjunto Habitacional Professora Mônica Borges Pagliuso", cep:"14775-060"},
{logradouro:"Rua do Lago", bairro:"Jaborandi", cep:"14775-126"},
{logradouro:"Rua Dom José de Matos Pereira", bairro:"Centro", cep:"14775-023"},
{logradouro:"Rua Dona Maria de Almeida Pinto Neto", bairro:"Nosso Teto", cep:"14775-092"},
{logradouro:"Rua Doutor Amadeu Pagliuso", bairro:"Centro", cep:"14775-013"},
{logradouro:"Rua Doutor Amadeu Pagliuso", bairro:"Conjunto Habitacional José Cardoso Batata", cep:"14775-200"},
{logradouro:"Rua Doutor Amadeu Pagliuso", bairro:"Jaborandi", cep:"14775-134"},
{logradouro:"Rua Elifas Ferreira de Araújo", bairro:"Centro", cep:"14775-025"},
{logradouro:"Rua Elifas Ferreira de Araújo", bairro:"Conjunto Habitacional Luiz Ferreira", cep:"14775-032"},
{logradouro:"Rua Elifas Ferreira de Araújo", bairro:"Conjunto Habitacional Noel Dionízio", cep:"14775-406"},
{logradouro:"Rua Elifas Ferreira de Araújo", bairro:"Jardim Palmares", cep:"14775-080"},
{logradouro:"Rua Elifas Ferreira de Araújo", bairro:"São Benedito", cep:"14775-380"},
{logradouro:"Rua Gabriel Diniz", bairro:"Conjunto Habitacional Agostinho Bruno", cep:"14775-334"},
{logradouro:"Rua Gabriel Diniz", bairro:"Conjunto Habitacional Antonio Baldo", cep:"14775-282"},
{logradouro:"Rua Gabriel Diniz", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-302"},
{logradouro:"Rua Gabriel Diniz", bairro:"Residencial Jaborandi I", cep:"14775-262"},
{logradouro:"Rua Gabriel Diniz", bairro:"São Benedito", cep:"14775-390"},
{logradouro:"Rua Gaspar Pereira dos Santos", bairro:"Jardim Primavera", cep:"14775-158"},
{logradouro:"Rua General Osório", bairro:"São Benedito", cep:"14775-392"},
{logradouro:"Rua Idalina Fonseca", bairro:"Jaborandi", cep:"14775-128"},
{logradouro:"Rua Inácio Maximo Diniz Junqueira", bairro:"Centro", cep:"14775-015"},
{logradouro:"Rua Inácio Maximo Diniz Junqueira", bairro:"Jaborandi", cep:"14775-124"},
{logradouro:"Rua Inácio Maximo Diniz Junqueira", bairro:"São Benedito", cep:"14775-372"},
{logradouro:"Rua Jair Pina", bairro:"Conjunto Habitacional Luiz Ferreira", cep:"14775-038"},
{logradouro:"Rua José Antônio Diniz Junqueira", bairro:"Centro", cep:"14775-003"},
{logradouro:"Rua José Antônio Diniz Junqueira", bairro:"Conjunto Habitacional José Cardoso Batata", cep:"14775-208"},
{logradouro:"Rua José Antônio Diniz Junqueira", bairro:"Conjunto Habitacional Luiz Ferreira", cep:"14775-040"},
{logradouro:"Rua José Antônio Diniz Junqueira", bairro:"Conjunto Habitacional Ronan Sales Cardozo", cep:"14775-220"},
{logradouro:"Rua José Brunozi", bairro:"Conjunto Habitacional José Cardoso Batata", cep:"14775-210"},
{logradouro:"Rua José Ferreira", bairro:"Conjunto Habitacional Ronan Sales Cardozo", cep:"14775-226"},
{logradouro:"Rua José Luiz Brunozi", bairro:"Conjunto Habitacional Antonio Baldo", cep:"14775-292"},
{logradouro:"Rua José Luiz Brunozi", bairro:"Residencial Jaborandi I", cep:"14775-274"},
{logradouro:"Rua José Pires da Silva", bairro:"Conjunto Habitacional Antonio Baldo", cep:"14775-290"},
{logradouro:"Rua José Pires da Silva", bairro:"Residencial Jaborandi I", cep:"14775-272"},
{logradouro:"Rua José Rodrigues Vieira", bairro:"Jardim Palmares", cep:"14775-076"},
{logradouro:"Rua Justino Fazzuoli", bairro:"Centro", cep:"14775-027"},
{logradouro:"Rua Justino Fazzuoli", bairro:"Conjunto Habitacional Luiz Ferreira", cep:"14775-034"},
{logradouro:"Rua Justino Fazzuoli", bairro:"Conjunto Habitacional Noel Dionízio", cep:"14775-404"},
{logradouro:"Rua Justino Fazzuoli", bairro:"Jardim Palmares", cep:"14775-078"},
{logradouro:"Rua Justino Fazzuoli", bairro:"São Benedito", cep:"14775-382"},
{logradouro:"Rua Karen Patrícia Domingues Tornelli", bairro:"Conjunto Habitacional Noel Dionízio", cep:"14775-412"},
{logradouro:"Rua Liberdade", bairro:"COHAB CRHIS", cep:"14775-352"},
{logradouro:"Rua Liberdade", bairro:"Conjunto Habitacional Antonio Baldo", cep:"14775-286"},
{logradouro:"Rua Liberdade", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-312"},
{logradouro:"Rua Liberdade", bairro:"Residencial Jaborandi I", cep:"14775-266"},
{logradouro:"Rua Liberdade", bairro:"São Benedito", cep:"14775-394"},
{logradouro:"Rua Luiz Daniel", bairro:"Centro", cep:"14775-011"},
{logradouro:"Rua Luiz Daniel", bairro:"Conjunto Habitacional Professora Mônica Borges Pagliuso", cep:"14775-054"},
{logradouro:"Rua Luiz Daniel", bairro:"Jaborandi", cep:"14775-136"},
{logradouro:"Rua Luiz Daniel", bairro:"Jardim Palmares", cep:"14775-072"},
{logradouro:"Rua Luiz Daniel", bairro:"Jardim Primavera", cep:"14775-150"},
{logradouro:"Rua Luiz Gambarato", bairro:"Conjunto Habitacional Antonio Baldo", cep:"14775-296"},
{logradouro:"Rua Luiz Gambarato", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-318"},
{logradouro:"Rua Luiz Gambarato", bairro:"Conjunto Habitacional Nossa Senhora Aparecida", cep:"14775-244"},
{logradouro:"Rua Manoel Bento Sobrinho", bairro:"Conjunto Habitacional Ronan Sales Cardozo", cep:"14775-224"},
{logradouro:"Rua Maria Antonieta Ferreira Salim", bairro:"Conjunto Habitacional Noel Dionízio", cep:"14775-402"},
{logradouro:"Rua Moacir Sales", bairro:"Conjunto Habitacional Professora Mônica Borges Pagliuso", cep:"14775-056"},
{logradouro:"Rua Odete Oliveira Vaz de Almeida", bairro:"Jardim Palmares", cep:"14775-074"},
{logradouro:"Rua Omar Sforcini", bairro:"Conjunto Habitacional Antonio Baldo", cep:"14775-294"},
{logradouro:"Rua Omar Sforcini", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-316"},
{logradouro:"Rua Omar Sforcini", bairro:"Conjunto Habitacional Nossa Senhora Aparecida", cep:"14775-246"},
{logradouro:"Rua Ribeirão das Palmeiras", bairro:"Conjunto Habitacional José Cardoso Batata", cep:"14775-202"},
{logradouro:"Rua Rio Pardo", bairro:"Conjunto Habitacional Professora Mônica Borges Pagliuso", cep:"14775-050"},
{logradouro:"Rua Santo Marçon", bairro:"Conjunto Habitacional Agostinho Bruno", cep:"14775-340"},
{logradouro:"Rua Santo Marçon", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-308"},
{logradouro:"Rua Sargento Carlos Xavier", bairro:"Conjunto Habitacional Ronan Sales Cardozo", cep:"14775-228"},
{logradouro:"Rua Seis", bairro:"Conjunto Habitacional Ronan Sales Cardozo", cep:"14775-230"},
{logradouro:"Rua Três", bairro:"Conjunto Habitacional Ronan Sales Cardozo", cep:"14775-222"},
{logradouro:"Rua Ulisses de Andreis", bairro:"Jaborandi", cep:"14775-142"},
{logradouro:"Rua Vercina Valéria de Araújo", bairro:"Residencial Jaborandi I", cep:"14775-270"},
{logradouro:"Rua Vereador Onofre Alves da Costa", bairro:"COHAB CRHIS", cep:"14775-358"},
{logradouro:"Rua Vereador Onofre Alves da Costa", bairro:"Conjunto Habitacional Jaborandi B", cep:"14775-322"},
{logradouro:"Rua Victório Gambarato", bairro:"Conjunto Habitacional José Cardoso Batata", cep:"14775-204"},
{logradouro:"Rua 13 de Maio", bairro:"São Benedito", cep:"14775-386"},
{logradouro:"Rua 15 de Novembro", bairro:"Centro", cep:"14775-001"},
{logradouro:"Rua 15 de Novembro", bairro:"Conjunto Habitacional Luiz Ferreira", cep:"14775-036"},
{logradouro:"Rua 15 de Novembro", bairro:"São Benedito", cep:"14775-384"},
{logradouro:"Rua 18 de Março", bairro:"Jaborandi", cep:"14775-122"},
{logradouro:"Rua 18 de Março", bairro:"Nosso Teto", cep:"14775-090"},
{logradouro:"Rua 7 de Setembro", bairro:"Conjunto Habitacional Antonio Baldo", cep:"14775-280"},
{logradouro:"Rua 7 de Setembro", bairro:"Conjunto Habitacional Nossa Senhora Aparecida", cep:"14775-250"},
{logradouro:"Rua 7 de Setembro", bairro:"Conjunto Habitacional Ronan Sales Cardozo", cep:"14775-236"},
{logradouro:"Rua 7 de Setembro", bairro:"Residencial Jaborandi I", cep:"14775-260"},
{logradouro:"Rua 7 de Setembro", bairro:"São Benedito", cep:"14775-388"},
{logradouro:"Travessa Casa dos Meus Sonhos", bairro:"Centro", cep:"14775-026"},
{logradouro:"Travessa Eliza Ferrari Buzetto", bairro:"Jaborandi", cep:"14775-132"}
]
